.editorconfig, .pre-commit-config.yaml, PULL_REQUEST_TEMPLATE.md
Adding
* Pull request template
* .editorconfig
* .pre-commit-config.yaml: only works if [pre-commit](https://pre-commit.com) is installed and ready. The used hooks require Go, but I don't think that would be a problem
=> Pull request template and minor repository tweaks

.pre-commit-config.yaml, Makefile, README.md, conf/configuration.go, config.toml, go.mod, go.sum, groups/configuration.go, groups/groups.go, groups_config.yaml, server.go
This commit adds the first functionality for the service, allowing it to load a YAML configuration file with the groups definitions in an structured way
- This change requires a documentation update
=> Group config parsing

server/errors.go, server/handlers.go
Removing `writer` argument from `handleError` because it is not used at all
Fixes #30 
Regular CI
=> Fix #30. Writer not used

Makefile
Executable used to run REST API tests is not cleared by using `make clean`
Fixes #52 
=> Fixed issue #52

checker/main.go
I forgot to change the output of an `append` call, which broke the "unkown tag" check. 
This is a simple fix of that.
`make before_commit`
=> Fix checker bug that reports all tags as unknown

server/server.go, tests/helpers/http.go
Minor fix to remove an unneeded parameter from `server.Initialize`
Fixes #65 
Regular CI
=> Remove initialize argument

Makefile, README.md, checker/main.go, content/content.go, openapi.json, server/handlers.go
This PR includes a modification over the current `content` endpoint, making it use `encoding/gob` encoder to produce a binary data to be sent over the network.
In addition, some changes into the static content data structures in order to reflect the current type of some of the fields (`string` instead `[]byte`), making it easier to consume by the Smart Proxy.
Fixes #45 
- This change requires a documentation update
Regular CI
=> Endpoint serving all content encoded with gob

tests/helpers/http.go
Due to changes on insights-operator-utils and its tests/helpers package, some changes are needed in the services
Regular CI
=> Minor helper fix in order to use operator-utils helpers

conf/configuration.go, content-service.go, content-service_test.go, content/content.go, content/content_test.go, content/errors.go, export_test.go, server/server.go, tests/content/no_reason/config.yaml, tests/content/no_reason/external/rules/rule1/err_key/metadata.yaml, tests/content/no_reason/external/rules/rule1/more_info.md, tests/content/no_reason/external/rules/rule1/plugin.yaml, tests/content/no_reason/external/rules/rule1/summary.md
One of the fields read from markdown files for rules is the `reason.md`. We just discovered that this file can live both at rule level and error key level, so the current parsing strategy doesn't fit very well with both possibilities.
This refactor intends to separate the parsing of the files and the validation of which fields are missing or not
Fixes #88 
Regular CI
=> Refactoring content parsing

Dockerfile
Currently, we build the container with the rules from master branch. We should download only tested `latest-release` ref.
Tested locally with:
```
buildah bud --build-arg GITHUB_API_TOKEN=token -f Dockerfile -t ics .
```
=> We should download only tested 'latest-release' of rules

Makefile
Avoid `docgo` to update `go.sum` and `go.mod`
Fixes #121 
Regular CI
=> Improve docgo generation in Makefile

openapi.json
No description found for endpoint `/content` and method `get`
Fixes #114
N/A
=> Fixed issue #114

openapi.json
No description found for endpoint `/groups` and method `get`
Fixes #113
N/A
=> Fixed issue #113

docs/packages/server/endpoints.html, docs/packages/server/handlers.html, docs/packages/server/server.html, docs/packages/server/server_test.html, server/handlers.go, server/server.go
This commit keeps the encoded static content in memory, in order to prevent that it is encoded for each HTTP request. This is a lazy-initialization approach: the encoded content will be generated when it is first needed
Fixes #133 
Regular CI
=> Adding encoded content to the instance to provent re-generating it

Dockerfile
In order to update the content on the production, the commit hash of the content service must be changed. It's not possible to update prod with new content if the code of the content-service wasn't changed. Therefore I propose to hardcode the content of the rules in the Dockerfile and update it when it needs. 
Fixes #144
Dockerfile is successfully built locally.
=> Hardcoded the version of ccx rules

Makefile, check_openapi.sh, openapi.json
Adds `/metrics` endpoint to OpenAPI specification for this service.
Fixes #210 
Regular CI
=> Fix #210. Add metrics endpoint to openapi.json

content/content.go, content/content_test.go, tests/content/ok/external/rules/rule1/err_key/metadata.yaml
Fix parsing issue detected in molodec and integration tests
Fixes #183 
Updated UTs
=> Fix error keys metadata retrieval when parsing rules content

content/content.go, content/content_test.go, tests/content/ok_metadata_empty_condition/config.yaml, tests/content/ok_metadata_empty_condition/external/rules/rule1/err_key/metadata.yaml, tests/content/ok_metadata_empty_condition/external/rules/rule1/more_info.md, tests/content/ok_metadata_empty_condition/external/rules/rule1/plugin.yaml, tests/content/ok_metadata_empty_condition/external/rules/rule1/summary.md, tests/content/ok_metadata_empty_condition/internal/rules/rule2/err_key/metadata.yaml, tests/content/ok_metadata_empty_condition/internal/rules/rule2/more_info.md, tests/content/ok_metadata_empty_condition/internal/rules/rule2/plugin.yaml, tests/content/ok_metadata_empty_condition/internal/rules/rule2/summary.md
All the rules that have metadata.yaml file have a condition field. But the tutorial rule (ccx-rules-ocm)
does not. This change fixes the behaviour where errorContent is not filled correctly if condition field is not
provided.
Fixes #218 
- Added new UT for this use case.
- Since tutorial_rule is the one affected, this behaviour will be checked in rule_content integration tests.
=> Take into account rules with empty contition (for tutorial rule)

.github/workflows/gh-pages.yml, build_deploy.sh, checker/main.go, content/content.go, content/content_test.go, deploy/clowdapp.yaml, pr_check.sh, tests/content/missing/external/rules/rule2/summary.md, tests/content/missing/internal/rules/rule3/summary.md, update_rules_content.sh
External rules used to have a requirement that the resolution steps must be filled in. For this reason, the `resolution.md` and `more_info.md` files were mandatory even if the resolution was unknown at the time. It was often worked around by providing these .md files empty.
This MR makes the presence of those files entirely optional, which increases the number of parsed rules from 48 to 55.
Because the attributes could've been empty before because of the empty .md files and according to Georgii and https://docs.google.com/document/d/1KxaZqxE0-Q2r3Y8KoVFBmbxfTHHQQA0Tu9jPMmI1P9E/edit?usp=sharing it won't break any UI element if `resolution` and `more_info` are `""`
Fixes CCXDEV-5058
- …
=> Resolution more info optional

Dockerfile
After setting everything up, Jose Luis tried running the Docker image locally and found out that haberdasher is causing duplicated and overwritten logs when ran as a Docker image (Thanks Jose). This DOES NOT happen when insights-content-service is ran locally and it only happens at the start of the service where the most important logs (rule content parsing) were overwritten by another message.
Temporarily disabling haberdasher to allow me to check the logs to help me with fixes for https://issues.redhat.com/browse/OCPBUGSM-31640 
Created a JIRA task to not forget to enable it later https://issues.redhat.com/browse/CCXDEV-5389
- Bug fix (???)
I hope CI will tell me that :grin:
=> temporarily disable haberdasher because of duplicated/overwritten logs

check_coverage.sh, checker/main.go, content/content.go, content/content_test.go
Recently we've allowed `summary.md`, `resolution.md` and `more_info.md` optional to enable rule developers. They've started adding a lot of content without these files.
reason.md should've been optional for a long time, the API is serving a `HasReason` flag for a long time, but it was actually never optional.
This PR fixes that.
Tested new rules before the changes, failed with same errors as in QA. Tested after the changes, works as expected.
=> make reason.md *actually* optional

PULL_REQUEST_TEMPLATE.md
Fix pull request template
Fixes #278
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Fix pull request template

go.mod, go.sum
Bump-up `utils` version to 1.21.0
N/A
=> Bump-up utils version to 1.21.0

content-service.go, content-service_test.go, export_test.go, openapi.json, server/endpoints.go, server/handlers.go, server/server.go, server/server_test.go
New `Info` endpoint that returns basic information about Content Service - version, commit hash, `utils` version etc.
Fixes #316
```
$ curl localhost:8080/api/v1/info | jq .
{
"info": {
"BuildBranch": "info-endpoint",
"BuildCommit": "a985007e982f6c82152e14c5436154525d176735",
"BuildTime": "Fri 29 Oct 2021 04:27:26 PM CEST",
"BuildVersion": "0.5",
"UtilsVersion": "v1.21.2"
},
"status": "ok"
}
```
=> New `Info` endpoint

.github/workflows/gh-pages.yml, Dockerfile, go.sum
Use [RHEL image](https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666?container-tabs=overview) with `go 1.16` version.
Fixes [CCXDEV-6472](https://issues.redhat.com/browse/CCXDEV-6472).
=> [CCXDEV-6472] Update go image version to 1.16

gosec.sh
Fixed `gosec`
Fixes #295
Can be checked on CI
=> Fixed `gosec`

content/content.go, groups/groups.go, server/server_test.go
Fixed deprecated `ioutil` calls
Fixes #361
Fixes #362
Fixes #363
Fixes #364
Fixes #365
Fixes #366
Done on CI
=> Fixed deprecated `ioutil` calls

build.sh, content-service.go, content-service_test.go
Pass the OCP rules version as build params and return the value in the `/info` endpoint.
Fixes #CXDEV-6834
**IMPORTANT**: this change will modify a v1 endpoint at smart proxy!
Content service:
```
❯ curl localhost:8080/api/v1/info | jq
{
"info": {
"BuildBranch": "master",
"BuildCommit": "e3cc637c1db1b1e1c0649d83c266c9a58842f89a",
"BuildTime": "Fri Jul  8 12:21:32 PM CEST 2022",
"BuildVersion": "0.1",
"OCPRulesVersion": "ccx-rules-ocp:2022.07.06",    <----------------
"UtilsVersion": "v1.22.0"
},
"status": "ok"
}
```
Smart Proxy:
```
❯ curl localhost:8081/api/v1/info | jq
{
"info": {
"SmartProxy": {
"BuildBranch": "CCXDEV-6834",
"BuildCommit": "4205beb1dc0bf46285fa5e334431c2b4afcda4ac",
"BuildTime": "Fri Jul  8 12:37:46 PM CEST …
```
=> [CCXDEV-6834] Show the ocp rules version in /info

Dockerfile, deploy/clowdapp.yaml
Minor change removing haberdasher references from the deployment files and Dockerfile
Fixes #[CCXDEV-8680](https://issues.redhat.com/browse/CCXDEV-8680)
Not at all, just removing unused vars
=> Clean up unused haberdasher vars and references

Dockerfile, build.sh, build_deploy.sh, update_rules_content.sh
This removes the dependency on ccx-rules-ocp image for building image. Rules are now directly cloned and bundled with the image.
=> [CCXDEV-8714] include ccx-rules-ocp directly, avoid rules image

CODEOWNERS
The file to update OCP rules version was changed. Dockerfile -> update_rules_content.sh
However, to allow automerging of  OCP rules version bump pull requests the filename has to be updated in CODEOWNERS.
=> Update CODEOWNERS with file for OCP rules versio bump MRs.

dashboards/grafana-dashboard-insights-ccx-insights-content-service.configmap.yaml
Move dashboard from saas-templates as it's been deprecated.
None.
=> [CCXDEV-9204] Move dashboard from saas-templates

pr_check.sh
Enable OCP Advisor UI tests for pull requests.
=> [CCXDEV-10204] pr_check.sh: enable ui tests

.travis.yml, README.md, build.sh, update_rules_content.sh
In order to build the service, the rules are needed. But downloading the ccx-ocp-rules is not needed in a testing environment.
CI
=> Build the service using only test rules in BDD tests

pr_check.sh
Workaround to skip pr_check for ocp rules version bump PR
#CCXDEV-10170
=> [CCXDEV-10170] workaround to skip pr_check for ocp rules version bump PR

build_deploy.sh
cc @tisnik :eyes: 
This change to the build_deploy.sh script is for the new security-compliance branch. It just adds a check if the current branch is security-compliance, and if it is it tags the image and pushes it up. 
This will only be called on merge to the branch from app-interface. I am going to create that job here shortly. 
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> Add check in build_deploy.sh to tag with security-compliance when that branch is built

README.md
=> Go language badge

Dockerfile
Old certificate will be removed next year and some servers are already requiring the new 2022 certificate issued in August 2023
https://issues.redhat.com/browse/CCXDEV-11664
https://source.redhat.com/groups/public/identity-access-management/rhcs_red_hat_certificate_system_wiki/faqs_new_corporate_root_certificate_authority
n/a
=> add new 2022-IT-Root-CA.pem certificate to Dockerfile

content/content.go
Since ccx-ocp-core v2023.08.30, the ocs rules are not a separate group of rules.
- `make test` pass
- service can be started properly and ocs rules are parsed (check logs)
=> Remove OCS rules group parsing

README.md
README now mentions how to start the service properly.
But the real goal of this PR is to get our rule release pipeline to pass (see https://gitlab.cee.redhat.com/ccx/ccx-rules-releaser/-/blob/master/scripts/common.sh#L41). Right now, the pipeline is trying to run the tests with the latest commit with message "Bumped ccx-rules-ocp version xxx", which was a version that could not be started properly due to the issue fixed in #506.
Fixes rule release ephemeral tests deployment
N/A
=> README fix with the objective of fixing release pipeline ephemeral deployment

dashboards/grafana-dashboard-insights-ccx-insights-content-service.configmap.yaml
The API response time panel was empty because of this typo.
UI.
=> Fix typo in dashboard

update_rules_content.sh
Reverts RedHatInsights/insights-content-service#544 because this has to be squashed for the rule release pipeline to pass
=> Revert "Bumped ccx-rules-ocp version"
