check_coverage.sh

Script to check code coverage

---

.travis.yml
Makefile
check_coverage.sh

Adding a simple Travis configuration file and testing in Travis if it works

CI configuration

---

check_coverage.sh
conf/configuration.go
conf/configuration_test.go
conf/export_test.go
export_test.go
go.mod
go.sum
groups/groups_test.go
logger/logger_test.go
openapi.json
server.go
server_test.go
storage/storage_test.go
tests/config.toml
tests/config_wrong_files.toml
types/types_test.go

Some unit tests for several packages to have some useful code coverage.
```
$ make test
./build.sh
ok      github.com/RedHatInsights/insights-content-service      0.003s  coverage: 41.9% of statements
ok      github.com/RedHatInsights/insights-content-service/conf 0.004s  coverage: 88.1% of statements
ok      github.com/RedHatInsights/insights-content-service/groups       0.029s  coverage: 100.0% of statements
ok      github.com/RedHatInsights/insights-content-service/logger       0.023s  coverage: [no statements] [no tests to run]
ok      github.com/RedHatInsights/insights-content-service/metrics      0.026s  coverage: [no statements] [no tests to run]
ok      github.com/RedHatInsights/insights-content-service/server       0.003s  coverage: 0.0% of …
```

Some unit tests

---

docs/index.md

Only adding a base `index.md` to make the GH Pages available
Fixes #15 
Not really

Adding index for GH Pages

---

.travis.yml
Makefile
test.sh
tests/rest/common.go
tests/rest/entrypoint.go
tests/rest/openapi.go
tests/rest/rest.go
tests/rest_api_tests.go

Stub for REST API tests
Run `make integration_tests`

Stub for rest api tests

---

go.mod
go.sum
groups/groups.go
openapi.json

Proposal on groups API endpoint and minimal implementation
Regular CI

Adding json annotations to format the output of the API and openapi update

---

server/handlers.go

Fixing the mismatch between OpenAPI and current implementation
Fixes #33 
Regular CI

Fixing mismatch between openapi defintion and current API

---

server/server.go

Method to stop HTTP server

---

server/server_test.go
tests/helpers/errors.go
tests/helpers/http.go
tests/helpers/timeout.go

Elementary tests for server module

Elementary tests for server module

---

Dockerfile

Adding a Dockerfile for building an image containing the compiled service
Regular CI

Adding a Dockerfile for building a basic container image

---

server/endpoints.go
server/errors.go
server/server_test.go
tests/helpers/http.go
tests/helpers/strings.go

Endpoints unit tests

---

server/configuration.go
server/server.go
server/server_test.go

Adding CORS headers and configuration option to enable/disable it
Regular CI

Adding CORS headers support

---

tests/rest/common.go
tests/rest/entrypoint.go
tests/rest/groups.go
tests/rest/openapi.go
tests/rest/rest.go

Rest (sic) of REST API tests
Fixes #39 
- Integration tests (no changes in the code)

Rest of REST API tests

---

check_coverage.sh
conf/configuration.go
conf/configuration_test.go
export_test.go
groups/groups.go
server/server.go
server/server_test.go
service.go
service_test.go
tests/config_improper_format.toml
tests/helpers/http.go

Rest of unit tests to maintain 80% threshold

Rest of unit tests

---

README.md

Add Codecov logo with link to README as usual in other repositories
Fixes #54

Add Codecov icon with link

---

Dockerfile

The resulting image should contain `group_config.yaml`.
Fixes #59 
Built locally with buildah

Added group_config.yaml into Dockerfile

---

Dockerfile
rules/tutorial/ccx_rules_ocm/__init__.py
rules/tutorial/ccx_rules_ocm/tutorial_rule.py
rules/tutorial/content/config.yaml
rules/tutorial/content/tutorial_rule/TUTORIAL_ERROR/generic.md
rules/tutorial/content/tutorial_rule/TUTORIAL_ERROR/metadata.yaml
rules/tutorial/content/tutorial_rule/more_info.md
rules/tutorial/content/tutorial_rule/plugin.yaml
rules/tutorial/content/tutorial_rule/summary.md

I added rules into the image because the pod cannot start:
```
{"level":"error","error":"open /rules-content/config.yaml: no such file or directory","time":"2020-06-11T08:16:36Z","message":"No rules directory"}
```
`buildah bud --build-arg GITHUB_API_TOKEN=some_toke -f Dockerfile -t ics `
`podman run -it -e INSIGHTS_CONTENT_SERVICE__SERVER__API_SPEC_FILE=/openapi/openapi.json INSIGHTS_CONTENT_SERVICE__GROUPS__PATH=/groups/groups_config.yaml localhost/ics`

Added rules content

---

server/configuration.go
server/server.go
server/server_test.go

Removing the CORS support from content-service, as it will be handled in smart-proxy
Fixes #47 
Regular CI

Removing CORS support

---

openapi.json

Minor fix on openapi spec
Fixes #89 
Regular CI

Fix strings/string in openapi.json spec

---

rules/tutorial/content/tutorial_rule/TUTORIAL_ERROR/metadata.yaml

Added tags to tutorial rule
Fixes https://github.com/RedHatInsights/insights-content-service/issues/92
...

Added tags to tutorial rule

---

conf/configuration.go
docs/packages/conf/configuration.html

Documentation for `conf` package.
Fixes #109 
Will be visible on GitHub pages.

Documentation for conf package

---

.gitignore
conf/configuration.go
config.toml
content-service.go
docs/ci.md
docs/configuration.md
docs/content_checker.md
docs/packages/conf/configuration.html
docs/packages/content-service.html
docs/prometheus.md
docs/testing.md
go.mod
go.sum

Added configuration support for defining a metrics namespace. Update the docs
Fixes #106 
Regular CI

Using namespaced metrics and updating docs

---

content-service.go
content-service_test.go
docs/packages/content-service.html
docs/packages/content-service_test.html

Use specific type for exit code
Done on CI

Use specific type for exit code

---

conf/export_test.go
docs/packages/conf/export_test.html
docs/packages/export_test.html
export_test.go

Comments for export test sources
Fixes #118
N/A

Comments for export test sources

---

conf/configuration.go
conf/configuration_test.go
config.toml
content-service.go
content-service_test.go
docs/configuration.md
docs/packages/conf/configuration.html
docs/packages/conf/configuration_test.html
docs/packages/content-service.html
docs/packages/content-service_test.html
docs/packages/export_test.html
export_test.go
tests/config.toml

Added `logging` section to the configuration in order to being able to set it to "debug" and use a human-readable console log messages.
Fixes #44 
Regular CI

Enable logging configuration

---

conf/export_test.go
docs/packages/conf/export_test.html
docs/packages/export_test.html
export_test.go

Slightly more info in comments in all `export_test.go` sources.
Fixes #118
N/A

Updates for fix 118

---

docs/ci.md

Updated main branch name in documentation.
Fixes #108
N/A

Fixed issue #108: main branch name

---

openapi.json

No description found for endpoint `/openapi.json` and method `get`
Fixes #112
N/A

Fixed issue #112

---

go.mod
go.sum
server/server_test.go

Blocked by https://github.com/RedHatInsights/insights-operator-utils/pull/106
`make before_commit`

some-fixes

---

docs/packages/server/server_test.html

Updated package to document
N/A

Updated package to document

---

docs/ci.md
docs/configuration.md
docs/prometheus.md
docs/role.md
docs/sequence_diagram.md
docs/testing.md

Sequence diagram on GitHub pages
N/A

Sequence diagram on GitHub pages

---

docs/architecture.md
docs/references.md

Link to insights data schemas repository
- Documentation update (does not change source code nor configuration)
N/A

Link to insights data schemas

---

Dockerfile

Add haberdasher (wrapper for message logging) to the Dockerfile

Add Haberdasher to Dockerfile

---

checker/main.go
content/content.go
content/content_test.go
content/errors.go
docs/packages/checker/main.html
docs/packages/content/content.html
docs/packages/content/errors.html
docs/packages/tests/helpers/helpers.html
docs/packages/tests/helpers/http.html
docs/packages/tests/rest/common.html
docs/packages/tests/rest/entrypoint.html
docs/packages/tests/rest/groups.html
docs/packages/tests/rest/openapi.html
docs/packages/tests/rest/rest.html
docs/packages/tests/rest_api_tests.html
docs/packages/types/types.html
docs/packages/types/types_test.html
tests/content/bad_metadata_condition/config.yaml
tests/content/bad_metadata_condition/external/rules/rule1/err_key/metadata.yaml
tests/content/bad_metadata_condition/external/rules/rule1/more_info.md
tests/content/bad_metadata_condition/external/rules/rule1/plugin.yaml
tests/content/bad_metadata_condition/external/rules/rule1/summary.md
tests/content/bad_metadata_condition/internal/rules/rule2/err_key/metadata.yaml
tests/content/bad_metadata_condition/internal/rules/rule2/more_info.md
tests/content/bad_metadata_condition/internal/rules/rule2/plugin.yaml
tests/content/bad_metadata_condition/internal/rules/rule2/summary.md
tests/content/ok/external/rules/rule1/err_key/metadata.yaml
tests/content/ok/internal/rules/rule2/err_key/metadata.yaml

This is a partial temporary fix for issue #183.
With this PR, the when metadata.yaml file is parsed, it no allows condition field
to be either a string (for backward compatibility) or a sequence of strings (new
rules including multiple error keys).
Fixes #183 
- Bug fix
- manual testing of content-service and smart-proxy to verify output content
- UTs:
- Added correct conditions field in existing rule contents test.
- Added incorrect conditions in tests/content/bad_metadata_condition and corresponding UT

Accept strings or list of strings as error condition in metadata.yaml

---

content/content.go
docs/packages/checker/main.html
docs/packages/conf/configuration.html
docs/packages/content-service.html
docs/packages/content/content.html
docs/packages/content/content_test.html
go.mod
go.sum

Display rules that are not loaded
Fixes #227
Done on CI and during deployment.

Display rules that are not loaded

---

Dockerfile

Used a container image as artifact storage with rules content.
- Deployment
Local image building finished successfully

Used container image as an artifact storage with rules content

---

conf/configuration.go
go.mod
go.sum

Clowder config stub

---

deploy/clowdapp.yaml

adds clowder manifest to allow the smart-proxy to be deployed into ephemeral envs
Fixes # CCXDEV-4921
- 
run
bonfire deploy -c ./bonfire-config-devel.yaml -n ephemeral-## ccx-data-pipeline and check after merging https://github.com/RedHatInsights/insights-results-smart-proxy/pull/547

add clowder manifest

---

deploy/clowdapp.yaml

Removed unneeded `Service` from `clowdapp.yaml`. Fixed port numbers.
Tested on the ephemeral environment.

Fixed clowdapp.yaml

---

content-service_test.go
content/content.go

Fixed typos

---

Dockerfile

Dockerfile update
registry.redhat.io/ubi8-minimal -> registry.access.redhat.com/ubi8/ubi-minimal:latest

[CCXDEV-5484] - update dockerfile

---

deploy/clowdapp.yaml

Added service to expose prometheus metrics
Fixes CCXDEV-5737

added prometheus exporter service

---

config-devel.toml

Debug option in `config-devel.toml`
- other
Used during local testing the service.

Debug option in config-devel.toml

---

content/content.go

Don't use magic constants

---

content-service.go
openapi.json
server/endpoints.go
server/handlers.go
server/server.go
server/server_test.go
tests/helpers/http.go
tests/rest/rest.go
tests/rest/status.go

Status endpoint minimal behaviour
Fixes #273
- REST API tests
Can be tried on CLI:
```
curl localhost:8080/status | jq .
```
Expected response:
```{
"rules": {
"bug_123456": {
"type": "external",
"loaded": true,
"error": ""
},
"ccxdev_auxiliary_rule": {
"type": "external",
"loaded": true,
"error": ""
},
"foobar_rule": {
"type": "internal",
"loaded": false,
"error": "some of the error keys are missing mandatory attributes"
}
}
"status": "ok"
}
```

Status endpoint minimal behaviour

---

Dockerfile

This reverts commit edf7730b1787a55267e32dcd3a95075a9bf54c59.

Revert "Bumped ccx-rules-ocp version"

---

Makefile
utils/json_check.py

Elementary JSON checker
Done on CI

Elementary JSON checker

---

content/content.go

Refactoring `fileinfo.Mode().IsRegular`
Fixes #319 
N/A

Refactoring `fileinfo.Mode().IsRegular`

---

server/server_test.go

Use `http.NoBody` explicitly
N/A

Use `http.NoBody` explicitly

---

conf/configuration.go

Check for empty string in configuration
N/A

Check for empty string in configuration

---

.travis.yml
openapi.json

Minor fix on Openapi specification to make check_openapi happy
Run ./check_openapi.sh locally

Fix openapi

---

deploy/clowdapp.yaml

added iqePlugin to clowdapp.yaml
Fixes # CCXDEV-6166
Check this CI pipeline

added iqePlugin to clowdapp

---

gosec.sh

Update `gosec.sh` - install latest gosec
Fixes #336 
Done on CI

Update `gosec.sh` - install latest gosec

---

content-service_test.go
tests/rest/groups.go
tests/rest/status.go

Idiomatic empty string tests
Done on CI

Idiomatic empty string tests

---

pr_check.sh

Attempt to fix failing pr_check.sh for ci.int.

[CCXDEV-7328] attempt to fix pr_check

---

conf/configuration_test.go
server/filters_test.go
server/server.go
tests/rest/common.go

Removed unused code
Done on CI

Removed unused code

---

.github/workflows/golangci-lint.yml
.golangci.yml

Setup Golang CI

---

.github/workflows/golangci-lint.yml
.travis.yml

Fix Travis problem regarding Nodejs version
N/A

Fix OpenAPI checks in Travis

---

tests/rest/groups.go

Fixed issue #375

---

server/filters_test.go

Fixes #373
Fixes #374
Done on CI

Fixes issues #373 and #374

---

checker/main.go
content-service.go

Fixed multiple issues: combine parameters
Fixes #369 
Fixes #370
Fixes #371 
Fixes #372 
Done on CI

Fixed multiple issues: combine parameters

---

content-service.go
server/server.go

Fix import shadow
Fixes #367 
Fixes #368
Done on CI

Fix import shadow

---

Dockerfile

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Behavioral tests (no changes in the code)
- REST API tests
- Benchmarks (no changes in the code)
Please describe how the change was …

Cleanup Dockerfile comments

---

server/server_test.go

Remove ioutil reference

---

.travis.yml
Makefile
README.md

Display code coverage on CI
Done on CI

Display code coverage on CI

---

deploy/clowdapp.yaml

Disable [minimum-replicas](https://github.com/stackrox/kube-linter/blob/main/docs/generated/templates.md#minimum-replicas) check used by [kube-linter](https://github.com/stackrox/kube-linter).
- Deployment (no changes in the code)
None.

[CCXDEV-8198] Disable minimum-replicas kube-linter check

---

deploy/clowdapp.yaml

Using the right annotation at https://github.com/RedHatInsights/insights-content-service/pull/418/files. ([Reference](https://github.com/stackrox/kube-linter/blob/main/docs/generated/checks.md#minimum-three-replicas)).

[CCXDEV-8198] Fix wrong annotation

---

goconst.sh
gocyclo.sh
goerrcheck.sh
gofmt.sh
golint.sh
govet.sh

Sync CI scripts - make them colorful
Done on CI

Sync CI scripts - make them colorful

---

server/server.go

Timeout for requests - avoid Slowloris
Done on CI

Timeout for requests - avoid Slowloris

---

gosec.sh

Latest `gosec.sh`

---

docs/ci.md

Info about `golangci lint`
N/A

Info about `golangci lint`

---

PULL_REQUEST_TEMPLATE.md

Pull request template security fix
Fixes #436
N/A

Pull request template security fix

---

pr_check.sh

Update pr_check.sh to run more tests in pull requests.
Fixes #CCXDEV-9706

[CCXDEV-9706] run more tests in pull requests

---

build_deploy.sh

…t branch is built
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Behavioral tests (no changes in the code)
- Security fix in dependent library (no changes in the code)
- Security fix in dependent library …

Add wildcards to security-compliance branch match

---

dashboards/grafana-dashboard-insights-ccx-insights-content-service.configmap.yaml

Use a fixed UID for the Grafana dashboard.
Part of #CCXDEV-10803

[CCXDEV-10803][Grafana] Use a fixed UID

---

build.sh

Use proper way to include tags (version info) into binary
To be checked on CI.

Use proper way to include tags (version info) into binary

---

pr_check.sh

Do not run UI tests as part of pr_checks
Related to [CCXDEV-11277](https://issues.redhat.com/browse/CCXDEV-11277)

Do not run UI tests as part of pr_checks

---

server/endpoints.go
server/handlers.go
server/server.go

Minor docstring fixes

---

content/content.go

Reduce nesting level
To be checked on CI.

Reduce nesting level

---

CODEOWNERS

Updated list of code owners
N/A

Updated list of code owners

---

checker/main.go
server/server.go
types/types.go

- Removed some formatted messages
- Fixed duplicated glitchtip errors
To be checked on CI.

Removed some formatted messages

---

.travis.yml

Simplify BDD stage in Travis by using the [run_in_container.sh script](https://github.com/RedHatInsights/insights-behavioral-spec/blob/main/run_in_docker.sh).
Fixes CCXDEV-10937
- Behavioral tests (no changes in the code)
CI

Update Travis BDD step to use run_in_container.sh script

---

tests/rest/groups.go
tests/rest_api_tests.go

Gofmt tests
- Other
Let's see what happens on CI.

Gofmt tests

---

deploy/clowdapp.yaml

Just using parameters in order to set the memory and CPU requests and limits from app-interface, making it easier and faster to configure.
CI.

[CCXDEV-12115] Add limits and requests parameters

---

.github/workflows/linters.yaml

Splitting CI linter jobs to be more  readable
Fixes # [(issue)](https://issues.redhat.com/browse/CCXDEV-12634)

Splitting linters CI jobs

---

deploy/clowdapp.yaml

Adding SENTRY_ENVIROMENT to clowdapp to enable GlitchTip

Add SENTRY_ENVIRONMENT to clowdapp

---

deploy/clowdapp.yaml

Fix of typo in sentry config

---

deploy/clowdapp.yaml

Fixing typo for logging to enable sentry. (Its supossed to be LOGGING__LOGING)

Fixing typo in logging config

---

deploy/clowdapp.yaml

Fixing typo in clowdapp deploy file for sentry configuration
Tested locally

Fixing typo in clowdapp sentry configuration

---

content-service.go

Removing the testing error log for glitchtip

Removing test error log for glitchtip

---

.github/workflows/linters.yaml

this is blocking the rule release
- 
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.

remove problematic errcheck from linters

---

renovate.json

enable auto-merge of konflux PRs when PR checks pass

[CCXDEV-14176] enable auto-merge of konflux PRs when PR checks pass

---

CODEOWNERS

[CCXDEV-14419] Remove CODEOWNERS file

---

.github/workflows/bots-automerge.yml

[CCXDEV-14404][CCXDEV-14176] Use Github-Actions to approve/automerge rules release and konflux PRs

[CCXDEV-14404][CCXDEV-14176] Use Github-Actions to approve/automerge rules release and konflux PRs

---

.github/workflows/bots-automerge.yml

[CCXDEV-14176] GH actions: add konflux/insightsdroid PR automerging

[CCXDEV-14176] GH actions: add konflux/insightsdroid PR automerging

---

.github/workflows/bots-automerge.yml

Removing self pr approval for InsightsDroid as it is not supported

[CCXDEV-14519]Removing unecesarry GH action

---

Dockerfile-konflux

Adding konflux specific dockerfile to reproduce specific error in konflux build-container
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.

Adding docker file for testing 

---

update_rules_content.sh

Setting the rules in content service to be the ones from runtimes PoC

[CCXDEV-14538] Change rules to be the ones for runtimes PoC
